name: Draft Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  cut-release:
    steps:
      - uses: actions/checkout@v3

      # Workflows cannot trigger other workflows implicitly
      # - https://github.community/t/github-actions-workflow-not-triggering-with-tag-push/17053/7
      - name: Bump Version and Push Tag
        if: github.repository == 'open-goal/jak-project'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          tag_prefix: v
          default_bump: ${{ github.event.inputs.bump }}

      # Generate the Release Notes
      # TODO
      # - name: Generate Release Notes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COMMIT_SHA: ${{ github.SHA }}
      #   run: |
      #     cd ./.github/workflows/scripts/releases/generate-release-notes
      #     npm ci
      #     node index.js
      #     mv ./release-notes.md ${GITHUB_WORKSPACE}/release-notes.md
      #     ls

      # Docs - https://github.com/softprops/action-gh-release
      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.repository == 'open-goal/jak-project' && steps.tag_version.outputs.new_tag
        with:
          draft: true
          prerelease: false
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
